project:
  type: website
  output-dir: docs
  execute-dir: project
  
website:
  title: "VibeCY"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: tab-one/tab-one-index.qmd
        text: Upcoming Events
      - href: tab-iframe/iframe-index.qmd
        text: Questionnaire
      - href: Tab2-iframe/iframe2-index.qmd
        text: Results
    logo: images/VibeCY.png

format:
  html:
    theme:
      - minty
      - playful
    css: styles.css
    toc: true
